export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_OUT = 'USER_LOGIN_OUT';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const USER_PHONE = 'USER_PHONE';
export const ACCESSTOKEN = 'ACCESSTOKEN';
export const USER_ID = 'USER_ID';
export const UPDATEUSERINFO = 'UPDATEUSERINFO';